### ISSUE TITLE
Deploy on Fly.io?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/learn-alpine.js#14]
Now that we have a Phoenix application with the drag and drop feature, it would be nice to test it.
- [ ] Deploy the application on Fly.io (not sure if the `flyctl deploy` command will work as a Phoenix application and node app coexists :thought_balloon: )

**Comment by nelsonic** [comment]
@SimonLab I think we can safely remove the node.js app ✂️ 
and just have a homepage with a menu of links for the various examples. 📝

**Comment by SimonLab** [comment]
I'm currently removing nodejs and convert our current [index.html](https://github.com/dwyl/learn-alpine.js/blob/main/index.html) and [stopwatch.html](https://github.com/dwyl/learn-alpine.js/blob/main/stopwatch.html) files to `heex` format to be used with Phoenix server.

Do we want to keep the [playground.html](https://dwyl.github.io/learn-alpine.js/playground.html) one, it looks like it is used mainly to test Alpine.js feature?

**Comment by nelsonic** [comment]
the `playground.html` is just a way of trying out a few ideas in Alpine.js ...
it would be cool if it was organised with section headings and a Table-of-contents like https://tachyons-bootstrap.dwyl.com/

For now, just `git mv` it to the appropriate folder and create a route `/playground` if you don't mind.
I will try and tidy it up on a future iteration. 💭

**Comment by SimonLab** [comment]
I've added Tailwind to Phoenix to make sure the existing examples (Stopwatch, and demo page) are displayed correctly.
However the UI for the drag and drop is now flat:
![image](https://user-images.githubusercontent.com/6057298/200298589-3da59503-aaba-4d80-b2b3-f29a83d42193.png)

I need to udpate it to make it look nice and update the Readme

**Comment by SimonLab** [comment]
UI updated:
![image](https://user-images.githubusercontent.com/6057298/200304238-5e5e11ef-3e83-4bf9-9578-9bc4678e9237.png)

I've copied some Tailwind classes from Petal components

**Comment by nelsonic** [comment]
https://alpine-demo.fly.dev/ 🚀 

You all have invites to **`admin`** the app on Fly.io 👌

**Comment by nelsonic** [comment]
https://github.com/dwyl/learn-alpine.js/settings/secrets/actions
![image](https://user-images.githubusercontent.com/194400/201483885-6d397172-bd74-4190-a590-cfffdc28ecec.png)

So auto-deploy should work. :shipit:

**Comment by nelsonic** [comment]
In our effort to support Fly.io and ensure they don't run out of cash from all the "Free Tier" Apps ...
we add $25 credit to all our apps:

![image](https://user-images.githubusercontent.com/194400/201484486-82da2804-fbe6-4ffd-8dd7-944d7f1b4bf5.png)

That way if they change their mind and charge us €1/month (or whatever it costs them to run these micro-apps) the money is already there. 👌
